### PR TITLE
only call set geometry when geometry actually should change

### PR DESCRIPTION
**Pull request by andres-asm**

### CODE REVIEW

**Review by Tatsuya79 — COMMENTED** [review]
It's not working as it should:
-a game starts up maximized at 512x243 (use PAR to be sure)
-when the resolution is changed during gameplay it's ignored
-the change only happens after changing parameters like scanline_start in core options

**Comment by andres-asm** [comment]
Ok, that's what I feared, gonna push another commit

**Comment by andres-asm** [comment]
Oh it has to react to changes in resolution during gameplay!
Ok hold on a bit.

**Comment by andres-asm** [comment]
Not sure what to test, I'm not really a PCE fan or a AR purist :)
Give it a shot please

**Comment by andres-asm** [comment]
it would be easier if you joined #retroarch in freenode btw

**Comment by Tatsuya79** [comment]
Too late for irc it's working perfectly now. :)

Thank you nice work.

**Comment by andres-asm** [comment]
Can you check an extra commit? 
I'm trying to add on the fly horizontal overscan switching

**Comment by Tatsuya79** [comment]
Ok that's what I was thinking to try to do now, funny.

**Comment by andres-asm** [comment]
this is the diff
http://hastebin.com/upeporocef.m

**Comment by Tatsuya79** [comment]
Nice that's working! I'll push it then, just tried locally.
Sorry got a long phone call...

**Pull request merged**
